#!/bin/sh
#
# A hook script that follows the symlink created by `npm link origraph` so that
# pre-release versions of the library are committed with the app

cp node_modules/origraph/dist/origraph.umd.js temp.js
rm -rf node_modules/origraph
mkdir node_modules/origraph
mkdir node_modules/origraph/dist
mv temp.js node_modules/origraph/dist/origraph.umd.js
git add node_modules/origraph/dist/origraph.umd.js
